# Create a data frame of GHCN daily datatypes and descriptions
ghcn_daily_datatypes <- data.frame(
  datatype = c(
    "PRCP", "SNOW", "SNWD", "TMAX", "TMIN", "TAVG", "AWND", "EVAP", "MDEV", "MDPR",
    "MDTN", "MDTX", "MNPN", "MXPN", "PGTM", "PSUN", "SN*#", "SX**", "THIC",
    "TOBS", "TSUN", "WDF1", "WDF2", "WDF5", "WDFI", "WDFM", "WDMV", "WESD", "WESF",
    "WSF1", "WSF2", "WSF5", "WSFI", "WSFM", "WT01", "WT02", "WT03", "WT04", "WT05",
    "WT06", "WT07", "WT08", "WT09", "WT10", "WT11", "WT12", "WT13", "WT14", "WT15",
    "WT16", "WT17", "WT18", "WT19", "WT21", "WT22",
    "ACMH", "ACSH", "FMTM", "GAHT", "WDFG", "WSFG", "WV01", "WV03"
  ),
  description = c(
    "Precipitation (tenths of mm)",
    "Snowfall (mm)",
    "Snow depth (mm)",
    "Maximum temperature (tenths of degrees Celsius)",
    "Minimum temperature (tenths of degrees Celsius)",
    "Average temperature (tenths of degrees Celsius)",
    "Average daily wind speed (tenths of meters per second)",
    "Evaporation of water from evaporation pan (tenths of mm)",
    "Multiday evaporation total (tenths of mm)",
    "Multiday precipitation total (tenths of mm)",
    "Multiday minimum temperature (tenths of degrees Celsius)",
    "Multiday maximum temperature (tenths of degrees Celsius)",
    "Daily minimum temperature of water in an evaporation pan (tenths of degrees Celsius)",
    "Daily maximum temperature of water in an evaporation pan (tenths of degrees Celsius)",
    "Peak gust time (hours and minutes, i.e., HHMM)",
    "Daily percent of possible sunshine (percent)",
    "Snow depth (mm)",
    "Snow, ice pellets, hail (mm)",
    "Thickness of ice on water (tenths of mm)",
    "Temperature at the time of observation (tenths of degrees Celsius)",
    "Daily total sunshine (minutes)",
    "Direction of fastest 1-minute wind (degrees)",
    "Direction of fastest 2-minute wind (degrees)",
    "Direction of fastest 5-second wind (degrees)",
    "Direction of highest instantaneous wind (degrees)",
    "Fastest mile wind direction (degrees)",
    "24-hour wind movement (km)",
    "Water equivalent of snow on the ground (tenths of mm)",
    "Water equivalent of snowfall (tenths of mm)",
    "Fastest 1-minute wind speed (tenths of meters per second)",
    "Fastest 2-minute wind speed (tenths of meters per second)",
    "Fastest 5-second wind speed (tenths of meters per second)",
    "Highest instantaneous wind speed (tenths of meters per second)",
    "Fastest mile wind speed (tenths of meters per second)",
    "Fog, ice fog, or freezing fog",
    "Heavy fog or heaving freezing fog (not always distinguished from 01)",
    "Thunder",
    "Ice pellets, sleet, snow pellets, or small hail",
    "Hail (may include small hail)",
    "Glaze or rime",
    "Dust, volcanic ash, blowing dust, blowing sand, or blowing obstruction",
    "Smoke or haze",
    "Blowing or drifting snow",
    "Tornado, waterspout, or funnel cloud",
    "High or damaging winds",
    "Blowing spray",
    "Mist",
    "Drizzle",
    "Freezing drizzle",
    "Rain (may include freezing rain, drizzle, and freezing drizzle)",
    "Freezing rain",
    "Snow, snow pellets, snow grains, or ice crystals",
    "Unknown source of precipitation",
    "Ground fog",
    "Ice fog or freezing fog",
    "Average Cloudiness Midnight to Midnight (percent)",
    "Average Cloudiness Sunrise to Sunset (percent)",
    "Time of Fastest Mile or Fastest 1-minute wind (hours and minutes, i.e., HHMM)",
    "Difference between river and gauge height (feet)",
    "Direction of peak wind gust (degrees)",
    "Peak gust wind speed (mph)",
    "Water equivalent of snow on the ground (inches)",
    "Water equivalent of snow on the ground (centimeters)"
  ),
  stringsAsFactors = FALSE
)

# Save the data frame as an R object
usethis::use_data(ghcn_daily_datatypes, overwrite = TRUE)
